/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CounterComposable: typeof import('./../components/CounterComposable.vue')['default']
    CounterStore: typeof import('./../components/CounterStore.vue')['default']
  }
}
